name: gh-release

on:
  push:
    tags:
      - "v*.*.*"
      - "v.*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create wheel package
        run: |
          pip install wheel
          python -m pip install --upgrade pip
          pip install check-wheel-contents
          python setup.py bdist_wheel
          check-wheel-contents ./dist
          gzip ./dist/*.whl
          ls -lh ./dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.gz
